[package]
name = "shilltube_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = '_'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
